# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

image: atlassian/default-image:3

pipelines:
  branches:
    develop:
    - step:
        script:
          - git remote add sync git@github.com:AnnoMMLXXVII/FantasyFranchiseAPI.git
          - git fetch sync
          - git remote rm sync
    - step:
        script:
          - git remote add sync git@github.com:AnnoMMLXXVII/FantasyFranchiseAPI.git
          - git checkout develop
          - git fetch
          - git pull
          - git push sync develop
    feature/*:
      - step:
          script:
          - git remote add sync git@github.com:AnnoMMLXXVII/FantasyFranchiseAPI.git
          - git push sync
   
