name: Deploy to BitBucket Remote
on:
  push:
    branches: ["develop", "feature/*"]
jobs:
  mirror-to-bitbucket:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        run: |
          git push --mirror bitbucket.org:AnnoMMLXXVII/FantasyFranchiseAPI.git