name: Deploy to BitBucket Remote
on:
  push:
    branches: ["develop", "feature/*"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Install SSH Key"
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }} 
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
      - name: Adding Known Hosts
          run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Deploy with rsync
          run: rsync -avz ./dist/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/zellwk/zellwk.com/dist/
      # - uses: actions/checkout@v2
      # - name: "Mirror Push"
      #   run: |
      #     ssh-keygen -t rsa -b 4096 -C "annommlxxvii@gmai.com"
      #     git push --mirror bitbucket.org:AnnoMMLXXVII/FantasyFranchiseAPI.git