name: Deploy to BitBucket Remote
on:
  push:
    branches: ["develop", "feature/*"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
      steps:
        - run: "git add remote sync https://AnnoMMLXXVII@bitbucket.org/AnnoMMLXXVII/fantasyfranchise.git;git push sync;"