name: Deploy to BitBucket Remote
on:
  push:
    branches: ["develop", "feature/*"]
jobs:
  mirror-to-bitbucket:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: 'Push'
        uses: ./
        id: mirror-to-bitbucket
        with:
          password: ${{secrets.BITBUCKET_SECRET}}